### ISSUE TITLE
Support GObject Introspection

### ISSUE THREAD

**Issue by eFrane** [zboxfs/zbox#14]
Would you consider supporting [GObject Introspection](https://wiki.gnome.org/action/show/Projects/GObjectIntrospection?action=show&redirect=GObjectIntrospection)?

This would allow using zbox from other programming languages. Support for introspection with Rust is still in the works but an example can be found here: https://github.com/sdroege/gobject-example-rs.

**Comment by burmecia** [comment]
I am not familiar with GObject, is this mainly for GTK app? Would it be easier if we provide native C/C++ FFI bindings?

**Comment by eFrane** [comment]
GObject was conceived for GTK apps, yes. But it has many applications beyond that. Native C/C++ bindings would be nice to, but wouldn't provide the same power.

**Comment by burmecia** [comment]
This feature won't be added. Close this issue for now.
