### ISSUE TITLE
Inconsistent `rename` behaviour

### ISSUE THREAD

**Issue by althonos** [zboxfs/zbox#26]
Hi @burmecia, 

just a quick hint about `Repo.rename` being described in [the documentation](https://docs.rs/zbox/0.5.0/zbox/struct.Repo.html#method.rename) as overwriting the destination if it already exists, while on the other hand the code has it return `Err(AlreadyExists)`.

You can test with the following cargo script:
```rust
// cargo-deps: zbox="*"
extern crate zbox;

fn main() {
    init_env();

    let mut repo = zbox::RepoOpener::new()
        .create(true)
        .open("file://./my_repo", "your password")
        .unwrap();

    let mut file = zbox::OpenOptions::new()
        .create(true)
        .open(&mut repo, "/my_file.txt")
        .unwrap();
    file.write_once(b"My file").unwrap();

    let mut file = zbox::OpenOptions::new()
        .create(true)
        .open(&mut repo, "/other_file.txt")
        .unwrap();
    file.write_once(b"Other file").unwrap();


    let res = repo.rename("/my_file.txt", "/other_file.txt");
    println!("{:?}", res)
}
```

**Comment by burmecia** [comment]
Yes, the `rename` has many inconsistencies with Rust's `fs.rename` operation, also the test cases are very limited. I will try to fix it in the next commit.
