### ISSUE TITLE
Issue with file reader after using `set_len`

### ISSUE THREAD

**Issue by althonos** [zboxfs/zbox#27]
Hi @burmecia,

another issue I stumbled upon (this is the last test case that fails against the pyfilesystem test suite): when a reader already exists for a file, extending the file with `set_len` and then reading the file (for instance with `read_to_end`) will not take into account the newly added bytes.

Here's a test case, that's shows that `file.read_to_end` will read the same file content twice although the call to `set_len` should extend the file:
```rust
// cargo-deps: zbox="*"
extern crate zbox;

use ::std::io::Read;
use ::std::io::Seek;
use ::std::io::SeekFrom;

fn main() {
    ::zbox::init_env();

    let mut repo = zbox::RepoOpener::new()
        .create(true)
        .open("mem://", "your password")
        .unwrap();

    let mut file = zbox::OpenOptions::new()
        .create(true)
        .write(true)
        .read(true)
        .open(&mut repo, "/my_file.txt")
        .unwrap();
    file.write_once(b"My file").unwrap();
    file.seek(SeekFrom::Start(0)).unwrap();

    let mut res = Vec::new();
    file.read_to_end(&mut res);
    println!("{:?}", res);

    file.set_len(15).unwrap();
    file.seek(SeekFrom::Start(0)).unwrap();

    let mut res2 = Vec::new();
    file.read_to_end(&mut res2);
    println!("{:?}", res2);
}
```

**Comment by burmecia** [comment]
That's an expected behaviour and I think that's probably the major difference with other FS.

Because Zbox is a versioned file system, the file reader is associated with a particular version when it is created. In the example code, when the file has been read the first time, a internal reader is created with its latest version. And then `set_len` will create a new version of file, but the internal reader still associated with the old version. So all the following read will still get the old content, which means the reader is invisible to new change.

A possible walk-around might be close the file and read again, or create a new `VersionReader` with latest version, that should be able to read the new content.

**Comment by althonos** [comment]
The cause of the error is actually what I suspected, but I honestly thought that calling `set_len` would force a new reader onto the file. This way, you would read a version only if opening through a versioned reader, and always read the latest version if using the file as a reader directly.

**Comment by burmecia** [comment]
That was actually what I originally thought, but later found many complicated scenario need to deal with so I simplified it to only allow 'static' reader on file.  You're right, the best is to keep consistent with normal file IO, file reader always read the latest version and specific `VersionReader` to read particular version. I think it is doable and should be the correct solution. I just need bit more time to think about how to implement it. Thank your for advice.

**Comment by althonos** [comment]
Ok, so I ended up using a version reader whenever I needed to work, and it works well. As a side note, I implemented the following function, and I think it could fit the `File` API (maybe with a boolean flag whether or not to seek the reader to the right position):
```rust
fn latest_reader(file, &mut ::zbox::File) -> zbox::Result<VersionReader> {
    let pos = file.seek(SeekFrom::Current(0))?;
    let version = file.curr_version()?;
    let mut reader = file.version_reader(version)?;
    reader.seek(SeekFrom::Start(pos));
    reader
}
```

**Comment by althonos** [comment]
Ok, so I ended up using a version reader whenever I needed to work, and it works well. As a side note, I implemented the following function, and I think it could fit the `File` API (maybe with a boolean flag whether or not to seek the reader to the right position) if you do not intend to change the current `read` / `read_to_end` behaviour:
```rust
fn latest_reader(file, &mut ::zbox::File) -> zbox::Result<VersionReader> {
    let pos = file.seek(SeekFrom::Current(0))?;
    let version = file.curr_version()?;
    let mut reader = file.version_reader(version)?;
    reader.seek(SeekFrom::Start(pos));
    reader
}
```

**Comment by burmecia** [comment]
Thanks for your advice. I made some changes to the file read/write, now the file reader is always on latest version. File read/write will also affect the file position, similar as Unix file operations. @althonos could you run test on the latest code?

**Comment by althonos** [comment]
@burmecia: the file reader passes all the test cases, great job !
