### ISSUE TITLE
Password Reset 

### ISSUE THREAD

**Issue by iamcharleschege** [zboxfs/zbox#33]
How do I reset the password for the zboxfs repository if I need to change it, I tried to look for the solution in the docs but there is none

**Comment by burmecia** [comment]
Hi @iamcharleschege , there is a `reset_password` method under `Repo` object.

https://docs.rs/zbox/0.6.1/zbox/struct.Repo.html#method.reset_password

**Comment by iamcharleschege** [comment]
Thank you. I wonder how I missed that
