### ISSUE TITLE
Zbox characteristics as a filesystem

### ISSUE THREAD

**Issue by vi** [zboxfs/zbox#58]
Most of README is about encryption and security, also some about backend support.

But I don't see typical filesystem metrics like maximum file size, maximum filesystem size, maximum number of files, overhead, fragmentation resilience and so on.

Shall README also mention those parameters?

For example, is zbox suitable for storage of very large number of small files? How slow is to delete those files afterwards?

**Comment by burmecia** [comment]
Good suggestion. I will update the README to add more about the characteristics soon. Thanks.

**Comment by vi** [comment]
> Maximum data file size (file storage) 	32 MiB

Does it mean files larger than 32 megabytes are not supported?

Or maybe it meat to be "gigabytes"?

**Comment by burmecia** [comment]
> > Maximum data file size (file storage) 	32 MiB
> 
> Does it mean files larger than 32 megabytes are not supported?
> 
> Or maybe it meat to be "gigabytes"?

No, 32 MiB data file size means each data file (encrypted) saved on the underlying file storage is maximun 32 MiB, the size limit of a file in ZboxFS is 16 EiB. One ZboxFS file can across one or many data files.

**Comment by vi** [comment]
Does it mean it only relevant in `file://` mode?

Maybe instead of "Maximum data file size (file storage)" it can be "Maximum underlying file size for `file://` storage"?

**Comment by burmecia** [comment]
> Does it mean it is only relevant in `file://` mode?
> 
> Maybe instead of "Maximum data file size (file storage)" it can be "Maximum underlying file size for `file://` storage"?

Yes, it is correct. I will put better wording later on.

**Comment by vi** [comment]
Does maximum file size depend on pointer width of the system ZboxFS is running on?

Is [`File::set_len`](https://docs.rs/zbox/0.8.8/zbox/struct.File.html#method.set_len) accepting `usize` instead of `u64` a deliberate design choice or oversight?
