### ISSUE TITLE
Example in README.md uses wrong method name

### ISSUE THREAD

**Issue by vbrandl** [zboxfs/zbox#6]
Your README.md uses the following code in the example:
```rust
use zbox::{zbox_init, RepoOpener, OpenOptions};
[...]
zbox_init();
```
While the init method is called `init_env`.

I think `zbox_init` would be the better name, from looking at it, you know that zbox will be initialized while `init_env` might be confusing (what env will be initialized?)

So I think you should rename the method to match the README, but if you won't change the API, you should still make the docs fit the code.

**Comment by burmecia** [comment]
Thanks @vbrandl . The `zbox_` prefix I think might be more suitable for FFI interfaces, I reserved that prefix for future FFI bindings. That's why I changed the name to `init_env`.

This has been fixed by 266e9c33d6fcf1388379159649a1e6fb822d2ed1
