### ISSUE TITLE
Is zbox::Repo::rename atomic?

### ISSUE THREAD

**Issue by vi** [zboxfs/zbox#71]
Does typical way of doing atomic filesystem changes (write temporary file, then rename it over actual file) work well with ZboxFS?

Either way, documentation of `zbox::Repo::rename` should mention atomicity.

Expected something like: "Even if ZBox is unexpectedly interrupted during the rename, either temporary file and original file should both exist and contain their respective contents, or only renamed file with the new content should exist".

Is situation where surprise-interrupted rename produces missing or zerolength file excluded?

**Comment by burmecia** [comment]
Yes, `zbox::Repo::rename` is an atomic method, so it is not necessary to it in the traditional way. The whole operation is put in one transaction, so either the renaming succeed or nothing is changed. There is no temporary file exist in any place.
